[workspace]
members = [
    "crates/themosis",
    "crates/themosis-cli",
    "crates/themosis-compiler",
    "crates/themosis-core",
    "crates/themosis-kdl",
    "crates/themosis-godot",
    "crates/themosis-godot-plugin",
    "crates/themosis-tokens",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
themosis = { path = "crates/themosis", version = "0.1.0" }
themosis-compiler = { path = "crates/themosis-compiler", version = "0.1.0" }
themosis-core = { path = "crates/themosis-core", version = "0.1.0" }
themosis-kdl = { path = "crates/themosis-kdl", version = "0.1.0" }
themosis-godot = { path = "crates/themosis-godot", version = "0.1.0" }
themosis-tokens = { path = "crates/themosis-tokens", version = "0.1.0" }

godot = { version = "=0.5.4", features = ["api-4-5"] }
kdl = { version = "=6.7.1", default-features = false, features = ["span"] }
serde = "1.0"
serde_json = "1.0"
tempfile = "3.27"
thiserror = "2.0"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
