[package]
name = "themosis-compiler"
description = "Semantic compiler for Themosis themes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
themosis-core.workspace = true

thiserror.workspace = true

[lints]
workspace = true
